### ISSUE TITLE
Find Symphony project logos

### ISSUE THREAD

**Issue by dankohn** [finos/finos-landscape#40] opened 2020-07-10 17:45 UTC
For v1 of the landscape, open items are:

- [ ] producing logos for all projects
- [x] Hiding the "FINOS Foundation Member Products/Projects" (which actually lists Members now)

We can consider adding Members at a later stage (I've raised https://github.com/finos/finos-landscape/issues/61) once: 

1) we have consolidated our metadata with the LF backend/crm infrastructure to single source information
2) we have decided our website strategy on the LF infra (i.e. will https://www.finos.org/members be sourced from the landscape)

--

Original issue from @dankohn:

Most of the logos are available using the search technique described in https://github.com/cncf/landscapeapp#images. For a small number, you will need to have our graphic designer recreate them.

Please create a Slack account on slack.cncf.io and open a channel with me and Alex Contini to discuss how we can help.

Once they're all added, we can add the member section to landscape view.

**Comment by mindthegab** [comment] 2020-07-10 19:23
@toshaellison who heads up our Marketing was working on logos so reassigning to her. And adding to our project for prioritization.

**Comment by dankohn** [comment] 2020-07-10 19:36
Many of them should be on https://lf-landscape.netlify.app/format=members

**Comment by brooklynrob** [comment] 2020-09-22 01:44
Do we need the members at all? I'm not sure what having them listed there adds, even if we did have logos.

At a minimum, can we change the text from "FINOS Foundation Member Products/Projects" to "FINOS Foundation Members". These are our "members", not our "Member Products/Projects".

![image](https://user-images.githubusercontent.com/2136904/93837255-65492900-fc53-11ea-8fb7-0dfc0af30404.png)

**Comment by dankohn** [comment] 2020-09-22 11:46
I highly recommend adding members. They very much appreciate being spotlighted. It is not a lot of work to get correct logos for each since most of them are CNCF members and have approved logos in the landscape.

On the landscape view, it will show members in their own box. See, for example, l.lfph.io. On card view, it shows members and member projects first, and then non-members and non-member projects second.

So, see for example: https://landscape.lfph.io/format=card-mode

**Comment by brooklynrob** [comment] 2020-09-22 13:27
Thanks @dankohn. I get that. @toshaellison, @mindthegab, me, etc are always looking for a way to increase value and to highlight our members . But I'm not sure how much value we're creating by having a bunch a FINOS logos under the label "FINOS Foundation Member Products/Projects" -- what's below that label are not "Member Products/Projects" but the "Members" themselves. So, back to my comment above, what would it take to change the label from "FINOS Foundation Member Products/Projects" to "FINOS Foundation Members"? I'll defer to @grizzwolf etc on collecting and uploaded the logos.

**Comment by dankohn** [comment] 2020-09-22 19:40
I feel like your landscape is 90% done, but it's hard for me to convince you that the extra 10% is going to make a huge difference.

Rather than having a bunch of identical FINOS logos, you want to create custom versions of logo that include the name of the project. That way, the landscape works even when it is embedded somewhere and you can't use the interactive version. But, you can still the names of each project. See how I've created custom flags with the location and project name as a header. You can create those custom SVGs at https://autocrop.cncf.io/.

And then including the logos of each member seem equally important.

You can change that item heading with this setting: https://github.com/finos/finos-landscape/blob/master/settings.yml#L59

**Comment by mindthegab** [comment] 2020-09-22 20:04
I feel we are conflating two conversations here. There's no doubt all projects will have to be there and with the right logo, and we're working on it.

Regarding Members, we already highlight them in the website https://www.finos.org/members and I don't see value in having another place where they are highlighted especially if that means we have to maintain yet another manual list (which would be the 4th place where we do that, i.e. our own metadata, the website, salesforce and hubspot).

@dankohn I appreciate sharing your experience with CNCF, but we have a very different community and I am happy to talk to you about the differences - banks actually generally don't care for (or don't want) their logo everywhere. 

So I vote to focus this issue on completing the logos for projects and hiding the member tab for now: once we have a single source of truth for Members, we can re-evaluate but the cost / benefit is skewed until then. 

I'll change the issue accordingly.

**Comment by dankohn** [comment] 2020-09-22 20:25
See the LFPH members page: https://www.lfph.io/join/members/. It embeds the landscape.

We have a project almost done to enable downloading the members from SFDC so that the member section gets auto-updated.

But, it's your landscape; you should use it how you think best.

**Comment by mindthegab** [comment] 2020-09-23 01:53
> See the LFPH members page: https://www.lfph.io/join/members/. It embeds the landscape.

Thanks @dankohn - cross posted at https://github.com/finos/finos-landscape/issues/61 as it's really good input.

> We have a project almost done to enable downloading the members from SFDC so that the member section gets auto-updated.

That is awesome. Thank you and I think it'll line up very nicely with our CRM migration - one more incentive for us to move quickly. I expect by end of year we should be in a much better place. 

> 
> But, it's your landscape; you should use it how you think best.

Thanks @dankohn. We really appreciate all the mentoring and support on the landscape, especially as we still have to fully switch out of our [FINOS catalog](https://finos.github.io/?sort=hotness-down). With all the moving parts (website, CRM, landscape<->catalog, easyCLA, etc.), we need to make sure we sequence things accordingly, but it's really valuable to get your advise on what our end game can be and so please keep it coming!

**Comment by maoo** [comment] 2020-09-29 17:30
Tried to work on `settings.yml` but didn't have luck, see https://github.com/finos/finos-landscape/pull/62 .

**Comment by maoo** [comment] 2020-10-06 10:36
Thanks to @AndreyKozlov1984 , the issue is now fixed, members have been hidden now. We'll keep this issue open to track the missing project logos.

**Comment by maoo** [comment] 2021-03-01 16:56
Closing in favour of #86

**Closed by maoo** 2021-03-01 16:56 UTC
Labels: enhancement
